# Generated by Django 2.0.1 on 2018-02-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desconocidos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testeo',
        ),
    ]
