# Generated by Django 2.0.1 on 2018-02-20 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desconocidos', '0001_initial'),
    ]

    operations = [





    ]
