# Generated by Django 2.0.1 on 2018-03-01 13:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_organismo_antieconomico'),
        ('desconocidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_finca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),

        migrations.AddField(
            model_name='desconocido',
            name='tipo_finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='desconocidos.tipo_finca'),
        ),

    ]
