# Generated by Django 2.0.1 on 2018-02-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desconocidos', '0004_actuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuacion',
            name='desconocido',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='desconocidos.Desconocido'),
        ),
    ]
