# Generated by Django 2.0.1 on 2018-02-15 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desconocidos', '0005_actuacion_desconocido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuacion',
            name='desconocido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desconocidos.Desconocido'),
        ),
    ]
