# Generated by Django 2.0.1 on 2018-02-15 21:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180215_1933'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desconocidos', '0006_auto_20180215_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='actuacion',
            new_name='actuaciones',
        ),
        migrations.AlterUniqueTogether(
            name='desconocido',
            unique_together={('fk_muni', 'refcat')},
        ),
    ]
