# Generated by Django 2.0.1 on 2018-02-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desconocidos', '0007_auto_20180215_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actuaciones',
            options={'verbose_name_plural': 'Actuaciones'},
        ),
        migrations.AddField(
            model_name='desconocido',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
