# Generated by Django 2.0.1 on 2018-02-16 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desconocidos', '0007_auto_20180216_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='desconocido',
            name='clave_uso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='desconocidos.usos'),
        ),
        migrations.AddField(
            model_name='desconocido',
            name='tipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='desconocidos.tipoDesc'),
        ),
    ]
