# Generated by Django 2.0.1 on 2018-02-19 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desconocidos', '0008_auto_20180215_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Tipos de desconocido',
            },
        ),
        migrations.CreateModel(
            name='usos',
            fields=[
                ('clave', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Usos',
            },
        ),
        migrations.AddField(
            model_name='actuaciones',
            name='agendar',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='actuaciones',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='clave_uso',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='desconocidos.usos'),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='cod_postal',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='dir_no_estruc',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='escalera',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='id_fiscal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='letra_pol',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='letra_pol_2',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='nombre_via',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='num_fijo',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='num_pol',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='num_pol_2',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='planta',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='puerta',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='refcat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='sigla_via',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='sujeto_pasivo',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='desconocido',
            name='tipo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='desconocidos.tipoDesc'),
        ),
    ]
