# Generated by Django 2.0.1 on 2018-02-16 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180216_0924'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desconocidos', '0008_auto_20180216_0922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='actuacion',
            new_name='actuaciones',
        ),
        migrations.AlterModelOptions(
            name='actuaciones',
            options={'verbose_name_plural': 'Actuaciones'},
        ),
        migrations.AddField(
            model_name='desconocido',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='desconocido',
            unique_together={('fk_muni', 'refcat')},
        ),
    ]
