# Generated by Django 2.0.1 on 2018-02-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desconocidos', '0010_auto_20180216_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desconocido',
            name='cod_postal',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='dir_no_estruc',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='escalera',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='id_fiscal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='letra_pol',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='letra_pol_2',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='nombre_via',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='num_fijo',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='num_pol',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='num_pol_2',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='planta',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='puerta',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='refcat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='sigla_via',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='desconocido',
            name='sujeto_pasivo',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
