# Generated by Django 2.0.1 on 2018-02-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desconocidos', '0011_auto_20180216_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desconocido',
            name='clave_uso',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='desconocidos.usos'),
        ),
    ]
