# Generated by Django 2.0.1 on 2018-02-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desconocidos', '0012_auto_20180216_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuaciones',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
