# Generated by Django 2.0.1 on 2018-02-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desconocidos', '0013_actuaciones_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuaciones',
            name='agendar',
            field=models.DateTimeField(null=True),
        ),
    ]
