# Generated by Django 2.0.1 on 2018-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desconocidos', '0014_actuaciones_agendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuaciones',
            name='agendar',
            field=models.DateField(null=True),
        ),
    ]
