# Generated by Django 2.0.1 on 2018-02-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desconocidos', '0009_auto_20180219_1226'),
        ('desconocidos', '0015_auto_20180216_1416'),
    ]

    operations = [
    ]
