# Generated by Django 2.0.1 on 2018-02-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('polls', '0002_finca'),
    ]

    operations = [
        migrations.CreateModel(
            name='organismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group')),
            ],
        ),
    ]
