# Generated by Django 2.0.1 on 2018-02-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='cod',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='cod',
            field=models.CharField(max_length=2),
        ),
    ]
