# Generated by Django 2.0.1 on 2018-02-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180215_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='cod',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='cod',
            field=models.IntegerField(max_length=2),
        ),
    ]
