# Generated by Django 2.0.1 on 2018-02-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180215_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('org', 'cod')},
        ),
    ]
