# Generated by Django 2.0.1 on 2018-02-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180215_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='tipo_impositivo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
