# Generated by Django 2.0.1 on 2018-02-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180216_1020'),
        ('polls', '0012_auto_20180219_1226'),
    ]

    operations = [
    ]
